---
- name: Ensures required package firewalld are installed
  ansible.builtin.include_tasks: fastpackages/install.yml
  vars:
    packages_list:
      - firewalld

- name: Enable and start the firewalld service
  become: yes
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Configure firewall for keycloak ports
  become: yes
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - "{{ keycloak_http_port }}/tcp"
    - "{{ keycloak_https_port }}/tcp"
    - "{{ keycloak_management_http_port }}/tcp"
    - "{{ keycloak_management_https_port }}/tcp"
    - "7600/tcp"
    - "8009/tcp"
