---
- name: Validate configuration
  assert:
    that:
      - (keycloak_ha_enabled and keycloak_db_enabled) or (not keycloak_ha_enabled and keycloak_db_enabled) or (not keycloak_ha_enabled and not keycloak_db_enabled)
    quiet: True
    fail_msg: "Cannot install HA setup without a backend database service. Check keycloak_ha_enabled and keycloak_db_enabled"
    success_msg: "{{ 'Configuring HA' if keycloak_ha_enabled else 'Configuring standalone' }}"

- name: Validate credentials
  assert:
    that:
      - (rhn_username is defined and rhsso_rhn_id is defined) or rhsso_rhn_id is not defined
      - (rhn_password is defined and rhsso_rhn_id is defined) or rhsso_rhn_id is not defined
    quiet: True
    fail_msg: "Cannot install Red Hat SSO without RHN credentials. Check rhn_username and rhn_password are defined"
    success_msg: "{{ 'Installing Red Hat Single Sign-On' if rhsso_rhn_id is defined else 'Installing keycloak.org' }}"

- name: Set required packages facts
  set_fact:
    required_packages:
    - "{{ jvm_package }}"
    - unzip
    - procps-ng
    - initscripts

- name: Ensures required packages are installed
  ansible.builtin.include_tasks: fastpackages/install.yml
  vars:
    packages_list: "{{ required_packages }}"