---
- name: Prepare
  hosts: all
  tasks:
    - name: Disable beta repos
      command: yum config-manager --disable '*beta*'
    - name: Install sudo
      yum:
        name: sudo
        state: present
