---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.keycloak
  tasks:
    - name: Include keycloak role
      include_role:
        name: keycloak
      vars:
        keycloak_admin_password: "changeme"