---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
  tasks:
    - name: Keycloak Role
      include_role:
        name: keycloak
      vars:
        keycloak_admin_password: "changeme"
    - name: Keycloak Realm Role
      include_role:
        name: keycloak_realm
      vars:
        keycloak_admin_password: "changeme"
        keycloak_realm: TestRealm
        keycloak_clients:
          - name: TestClient1
            roles:
              - TestClient1Admin
              - TestClient1User
            realm: "{{ keycloak_realm }}"
            public_client: True
            web_origins:
              - http://testclient1origin/application
              - http://testclient1origin/other
            users:
            - username: TestUser
              password: password
              client_roles:
                - client: TestClient1
                  role: TestClient1User
                  realm: "{{ keycloak_realm }}"
