---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - middleware_automation.redhat_csp_download.redhat_csp_download
  tasks:
    - name: Keycloak Role
      ansible.builtin.include_role:
        name: middleware_automation.keycloak.keycloak
      vars:
        keycloak_admin_password: "changeme"
        keycloak_rhsso_enable: True